-- Ayu Dark background + Catppuccin Mocha syntax/UI colors
-- Mocha palette
local M = {
  rosewater = "#F5E0DC",
  flamingo  = "#F2CDCD",
  pink      = "#F5C2E7",
  mauve     = "#CBA6F7",
  red       = "#F38BA8",
  maroon    = "#EBA0AC",
  peach     = "#FAB387",
  yellow    = "#F9E2AF",
  green     = "#A6E3A1",
  teal      = "#94E2D5",
  sky       = "#89DCEB",
  sapphire  = "#74C7EC",
  blue      = "#89B4FA",
  lavender  = "#B4BEFE",
  text      = "#CDD6F4",
  subtext1  = "#BAC2DE",
  subtext0  = "#A6ADC8",
  overlay2  = "#9399B2",
  overlay1  = "#7F849C",
  overlay0  = "#6C7086",
  surface2  = "#585B70",
  surface1  = "#45475A",
  surface0  = "#313244",
  -- ayu-dark bg instead of mocha base
  base      = "#141414",
  mantle    = "#0e0e0e",
  crust     = "#0a0a0a",
}

return {
  {
    "Shatur/neovim-ayu",
    lazy = false,
    priority = 1000,
    config = function()
      require("ayu").setup({
        mirage = false,
        overrides = function()
          return {
            -- ── Base UI ──────────────────────────────────────────────
            Normal          = { fg = M.text,     bg = M.base },
            NormalFloat     = { fg = M.text,     bg = M.mantle },
            FloatBorder     = { fg = M.blue,     bg = M.mantle },
            FloatTitle      = { fg = M.blue,     bg = M.mantle },
            NormalNC        = { fg = M.text,     bg = M.base },
            SignColumn      = { fg = M.surface1, bg = M.base },
            ColorColumn     = {                  bg = M.surface0 },
            CursorLine      = {                  bg = M.surface0 },
            CursorLineNr    = { fg = M.lavender, bold = true },
            LineNr          = { fg = M.overlay1 },
            VertSplit       = { fg = M.surface1 },
            WinSeparator    = { fg = M.surface1 },
            Folded          = { fg = M.blue,     bg = M.surface0 },
            FoldColumn      = { fg = M.overlay1, bg = M.base },
            EndOfBuffer     = { fg = M.surface0 },
            Conceal         = { fg = M.overlay2 },
            MatchParen      = { fg = M.peach,    bold = true, underline = true },
            Visual          = {                  bg = M.surface2 },
            Search          = { fg = M.base,     bg = M.yellow },
            IncSearch       = { fg = M.base,     bg = M.peach },
            Substitute      = { fg = M.base,     bg = M.red },
            WildMenu        = { fg = M.base,     bg = M.blue },

            -- ── Popup / completion menu ───────────────────────────────
            Pmenu           = { fg = M.text,     bg = M.surface0 },
            PmenuSel        = { fg = M.base,     bg = M.blue },
            PmenuSbar       = {                  bg = M.surface1 },
            PmenuThumb      = {                  bg = M.overlay0 },

            -- ── Status / tab line ─────────────────────────────────────
            StatusLine      = { fg = M.text,     bg = M.mantle },
            StatusLineNC    = { fg = M.overlay1, bg = M.mantle },
            TabLine         = { fg = M.overlay1, bg = M.mantle },
            TabLineSel      = { fg = M.text,     bg = M.surface1 },
            TabLineFill     = {                  bg = M.crust },

            -- ── Syntax ────────────────────────────────────────────────
            Comment         = { fg = M.overlay1, italic = true },
            String          = { fg = M.green },
            Character       = { fg = M.teal },
            Number          = { fg = M.peach },
            Float           = { fg = M.peach },
            Boolean         = { fg = M.peach },
            Identifier      = { fg = M.flamingo },
            Function        = { fg = M.blue },
            Keyword         = { fg = M.mauve },
            Conditional     = { fg = M.mauve },
            Repeat          = { fg = M.mauve },
            Label           = { fg = M.mauve },
            Operator        = { fg = M.sky },
            Exception       = { fg = M.mauve },
            Statement       = { fg = M.mauve },
            Include         = { fg = M.mauve },
            Define          = { fg = M.mauve },
            Macro           = { fg = M.mauve },
            PreProc         = { fg = M.pink },
            PreCondit       = { fg = M.mauve },
            Type            = { fg = M.yellow },
            StorageClass    = { fg = M.yellow },
            Structure       = { fg = M.yellow },
            Typedef         = { fg = M.yellow },
            Special         = { fg = M.peach },
            SpecialChar     = { fg = M.peach },
            Tag             = { fg = M.peach },
            Delimiter       = { fg = M.overlay2 },
            SpecialComment  = { fg = M.blue, italic = true },
            Underlined      = { fg = M.blue, underline = true },
            Bold            = { bold = true },
            Italic          = { italic = true },
            Error           = { fg = M.red },
            Todo            = { fg = M.base, bg = M.yellow, bold = true },

            -- ── Treesitter ────────────────────────────────────────────
            ["@comment"]              = { fg = M.overlay1, italic = true },
            ["@comment.documentation"]= { fg = M.overlay2, italic = true },
            ["@punctuation.delimiter"]= { fg = M.overlay2 },
            ["@punctuation.bracket"]  = { fg = M.overlay2 },
            ["@punctuation.special"]  = { fg = M.sky },
            ["@string"]               = { fg = M.green },
            ["@string.escape"]        = { fg = M.pink },
            ["@string.special"]       = { fg = M.teal },
            ["@string.regex"]         = { fg = M.peach },
            ["@character"]            = { fg = M.teal },
            ["@number"]               = { fg = M.peach },
            ["@float"]                = { fg = M.peach },
            ["@boolean"]              = { fg = M.peach },
            ["@constant"]             = { fg = M.peach },
            ["@constant.builtin"]     = { fg = M.peach },
            ["@constant.macro"]       = { fg = M.mauve },
            ["@namespace"]            = { fg = M.lavender },
            ["@symbol"]               = { fg = M.flamingo },
            ["@variable"]             = { fg = M.text },
            ["@variable.builtin"]     = { fg = M.red },
            ["@variable.parameter"]   = { fg = M.maroon },
            ["@variable.member"]      = { fg = M.lavender },
            ["@function"]             = { fg = M.blue },
            ["@function.builtin"]     = { fg = M.peach },
            ["@function.call"]        = { fg = M.sapphire },
            ["@function.macro"]       = { fg = M.teal },
            ["@function.method"]      = { fg = M.blue },
            ["@function.method.call"] = { fg = M.sapphire },
            ["@constructor"]          = { fg = M.sapphire },
            ["@keyword"]              = { fg = M.mauve },
            ["@keyword.function"]     = { fg = M.mauve },
            ["@keyword.operator"]     = { fg = M.mauve },
            ["@keyword.return"]       = { fg = M.mauve },
            ["@keyword.import"]       = { fg = M.mauve },
            ["@keyword.conditional"]  = { fg = M.mauve },
            ["@keyword.repeat"]       = { fg = M.mauve },
            ["@keyword.exception"]    = { fg = M.mauve },
            ["@operator"]             = { fg = M.sky },
            ["@type"]                 = { fg = M.yellow },
            ["@type.builtin"]         = { fg = M.yellow },
            ["@type.definition"]      = { fg = M.yellow },
            ["@attribute"]            = { fg = M.flamingo },
            ["@property"]             = { fg = M.lavender },
            ["@label"]                = { fg = M.blue },
            ["@tag"]                  = { fg = M.mauve },
            ["@tag.attribute"]        = { fg = M.green },
            ["@tag.delimiter"]        = { fg = M.sky },

            -- ── Diagnostics ───────────────────────────────────────────
            DiagnosticError           = { fg = M.red },
            DiagnosticWarn            = { fg = M.yellow },
            DiagnosticInfo            = { fg = M.sky },
            DiagnosticHint            = { fg = M.teal },
            DiagnosticOk              = { fg = M.green },
            DiagnosticUnderlineError  = { sp = M.red,    underline = true },
            DiagnosticUnderlineWarn   = { sp = M.yellow, underline = true },
            DiagnosticUnderlineInfo   = { sp = M.sky,    underline = true },
            DiagnosticUnderlineHint   = { sp = M.teal,   underline = true },
            DiagnosticVirtualTextError= { fg = M.red,    bg = M.crust },
            DiagnosticVirtualTextWarn = { fg = M.yellow, bg = M.crust },
            DiagnosticVirtualTextInfo = { fg = M.sky,    bg = M.crust },
            DiagnosticVirtualTextHint = { fg = M.teal,   bg = M.crust },

            -- ── LSP ───────────────────────────────────────────────────
            LspReferenceText          = {                  bg = M.surface2 },
            LspReferenceRead          = {                  bg = M.surface2 },
            LspReferenceWrite         = {                  bg = M.surface2 },
            LspInlayHint              = { fg = M.overlay1, bg = M.mantle, italic = true },

            -- ── Git signs ─────────────────────────────────────────────
            GitSignsAdd               = { fg = M.green },
            GitSignsChange            = { fg = M.yellow },
            GitSignsDelete            = { fg = M.red },
            DiffAdd                   = {                  bg = "#1e2b1e" },
            DiffChange                = {                  bg = "#2b271e" },
            DiffDelete                = { fg = M.red,     bg = "#2b1e1e" },
            DiffText                  = {                  bg = "#3b3418" },

            -- ── Telescope ─────────────────────────────────────────────
            TelescopeNormal           = { fg = M.text,     bg = M.mantle },
            TelescopeBorder           = { fg = M.blue,     bg = M.mantle },
            TelescopePromptNormal     = { fg = M.text,     bg = M.surface0 },
            TelescopePromptBorder     = { fg = M.blue,     bg = M.surface0 },
            TelescopePromptTitle      = { fg = M.base,     bg = M.blue },
            TelescopePreviewTitle     = { fg = M.base,     bg = M.green },
            TelescopeResultsTitle     = { fg = M.base,     bg = M.mauve },
            TelescopeSelection        = { fg = M.text,     bg = M.surface1 },
            TelescopeSelectionCaret   = { fg = M.blue },
            TelescopeMatching         = { fg = M.peach,    bold = true },

            -- ── Neo-tree ──────────────────────────────────────────────
            NeoTreeNormal             = { fg = M.text,     bg = M.mantle },
            NeoTreeNormalNC           = { fg = M.text,     bg = M.mantle },
            NeoTreeVertSplit          = { fg = M.crust,    bg = M.crust },
            NeoTreeWinSeparator       = { fg = M.crust,    bg = M.crust },
            NeoTreeEndOfBuffer        = { fg = M.mantle,   bg = M.mantle },
            NeoTreeRootName           = { fg = M.blue,     bold = true },
            NeoTreeGitAdded           = { fg = M.green },
            NeoTreeGitDeleted         = { fg = M.red },
            NeoTreeGitModified        = { fg = M.yellow },
            NeoTreeGitConflict        = { fg = M.red,      bold = true },
            NeoTreeGitUntracked       = { fg = M.mauve },
            NeoTreeIndentMarker       = { fg = M.overlay0 },
            NeoTreeExpander           = { fg = M.overlay2 },
            NeoTreeDirectoryName      = { fg = M.blue },
            NeoTreeDirectoryIcon      = { fg = M.blue },
            NeoTreeFileIcon           = { fg = M.text },
            NeoTreeFileName           = { fg = M.text },
            NeoTreeFileNameOpened     = { fg = M.flamingo },
            NeoTreeDotfile            = { fg = M.overlay1 },
            NeoTreeSymbolicLinkTarget = { fg = M.pink },
            NeoTreeTitleBar           = { fg = M.base,     bg = M.blue },
            NeoTreeFilterTerm         = { fg = M.green,    bold = true },

            -- ── Indent / context ─────────────────────────────────────
            IndentBlanklineChar             = { fg = M.surface1 },
            IndentBlanklineContextChar      = { fg = M.surface2 },
            IblIndent                       = { fg = M.surface1 },
            IblScope                        = { fg = M.surface2 },

            -- ── WhichKey ─────────────────────────────────────────────
            WhichKey               = { fg = M.lavender },
            WhichKeyGroup          = { fg = M.blue },
            WhichKeyDesc           = { fg = M.text },
            WhichKeySeparator      = { fg = M.overlay0 },
            WhichKeyValue          = { fg = M.overlay2 },
            WhichKeyFloat          = { bg = M.mantle },
            WhichKeyBorder         = { fg = M.blue, bg = M.mantle },
          }
        end,
      })
      vim.cmd.colorscheme("ayu-dark")
    end,
  }
}
